//! Literal environment precedence, separate from Cargo's child-process [env].

use std::collections::BTreeMap;

use sha2::{Digest, Sha256};

use crate::config::execution::supported_environment_key;
use crate::limits;

use super::Failure;

/// Private bounded effective environment. Values must not enter diagnostics.
#[derive(Clone)]
pub struct Environment {
    values: BTreeMap<String, String>,
    origins: BTreeMap<String, Origin>,
}

/// Safe provenance categories with no raw value or path.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Origin {
    /// Protected inherited launcher declaration.
    Protected,
    /// Explicit client environment field.
    Client,
    /// Literal leading shell assignment.
    Assignment,
    /// Literal env wrapper assignment, unset or clear.
    Wrapper,
    /// Cargo child-process [env], distinct from Cargo's own process inputs.
    CargoConfig,
    /// Fixed values generated by the pinned rustup process, never user input.
    Rustup,
    /// Fixed Cargo-generated secondary executable identity.
    Cargo,
    /// Fixed Clippy-generated compiler wrapper/arguments.
    Clippy,
}

/// Validate one literal environment name before treating it as assignment data.
#[must_use]
pub fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.bytes().enumerate().all(|(index, byte)| {
            byte == b'_' || byte.is_ascii_alphabetic() || (index != 0 && byte.is_ascii_digit())
        })
}

impl Environment {
    /// Start from the protected inherited environment, never ambient hook data.
    ///
    /// # Errors
    /// Unknown keys and overflowing declarations fail conservatively.
    pub fn inherited(values: &BTreeMap<String, String>) -> Result<Self, Failure> {
        let mut environment = Self {
            values: BTreeMap::new(),
            origins: BTreeMap::new(),
        };
        for (key, value) in values {
            environment.set(key, Some(value), Origin::Protected)?;
        }
        Ok(environment)
    }

    /// Apply one literal assignment or unset with its distinct origin.
    ///
    /// # Errors
    /// Unknown path/executable mechanisms, NUL and overflow deny.
    pub fn set(&mut self, key: &str, value: Option<&str>, origin: Origin) -> Result<(), Failure> {
        if !valid_name(key) || !supported_environment_key(key) {
            return Err(Failure::Environment);
        }
        if value.is_some_and(|value| value.len() > limits::PATH_BYTES || value.contains('\0')) {
            return Err(Failure::Limit);
        }
        if let Some(value) = value {
            self.values.insert(key.to_owned(), value.to_owned());
        } else {
            self.values.remove(key);
        }
        self.origins.insert(key.to_owned(), origin);
        if self.values.len() > limits::EXECUTION_ENVIRONMENT
            || self.origins.len() > limits::EXECUTION_ENVIRONMENT
        {
            return Err(Failure::Limit);
        }
        Ok(())
    }

    /// Rustup-generated mechanisms have a separate private write boundary.
    /// User/client/config assignment validation never accepts loader or recursion
    /// variables. The execution proof layer computes these exact values.
    pub(super) fn generated(&mut self, key: &str, value: &str) -> Result<(), Failure> {
        if !matches!(
            key,
            "PATH"
                | "CARGO_HOME"
                | "RUSTUP_HOME"
                | "RUSTUP_TOOLCHAIN"
                | "LD_LIBRARY_PATH"
                | "RUST_RECURSION_COUNT"
        ) {
            return Err(Failure::Environment);
        }
        self.fixed_generated(key, value, Origin::Rustup)
    }

    pub(super) fn cargo_generated(&mut self, key: &str, value: &str) -> Result<(), Failure> {
        if key != "CARGO" {
            return Err(Failure::Environment);
        }
        self.fixed_generated(key, value, Origin::Cargo)
    }

    pub(super) fn clippy_generated(&mut self, key: &str, value: &str) -> Result<(), Failure> {
        if !matches!(key, "RUSTC_WORKSPACE_WRAPPER" | "CLIPPY_ARGS") {
            return Err(Failure::Environment);
        }
        self.fixed_generated(key, value, Origin::Clippy)
    }

    fn fixed_generated(&mut self, key: &str, value: &str, origin: Origin) -> Result<(), Failure> {
        if value.len() > limits::PATH_BYTES || value.contains('\0') {
            return Err(Failure::Limit);
        }
        self.values.insert(key.to_owned(), value.to_owned());
        self.origins.insert(key.to_owned(), origin);
        if self.values.len() > limits::EXECUTION_ENVIRONMENT
            || self.origins.len() > limits::EXECUTION_ENVIRONMENT
        {
            return Err(Failure::Limit);
        }
        Ok(())
    }

    /// Model env -i explicitly; removed keys remain represented in provenance.
    pub fn clear(&mut self) {
        self.values.clear();
        for origin in self.origins.values_mut() {
            *origin = Origin::Wrapper;
        }
    }

    /// Read private effective data for static path resolution.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<&str> {
        self.values.get(key).map(String::as_str)
    }

    /// Effective private map, for domain-separated provenance hashing.
    #[must_use]
    pub fn values(&self) -> &BTreeMap<String, String> {
        &self.values
    }

    /// Safe origin of a present or explicitly removed key.
    #[must_use]
    pub fn origin(&self, key: &str) -> Option<Origin> {
        self.origins.get(key).copied()
    }

    /// Private values and all provenance, including explicitly removed keys.
    /// Hashes are not encryption; callers must not expose private maps.
    pub(super) fn digest(&self) -> [u8; 32] {
        let mut hash = Sha256::new();
        hash.update(b"memory-hooks-rust-environment-v1\0");
        for (key, origin) in &self.origins {
            hash.update(key.len().to_be_bytes());
            hash.update(key.as_bytes());
            hash.update([match origin {
                Origin::Protected => 0,
                Origin::Client => 1,
                Origin::Assignment => 2,
                Origin::Wrapper => 3,
                Origin::CargoConfig => 4,
                Origin::Rustup => 5,
                Origin::Cargo => 6,
                Origin::Clippy => 7,
            }]);
            if let Some(value) = self.values.get(key) {
                hash.update([1]);
                hash.update(value.len().to_be_bytes());
                hash.update(value.as_bytes());
            } else {
                hash.update([0]);
            }
        }
        hash.finalize().into()
    }
}
